apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomize will add the namespace and labels to all files being kustomized
namespace: tekton-argocd-example
commonLabels:
  pipeline: tekton
  deploy: argocd

resources:
- resources/docker-credentials.yml
- resources/event-listener.yml
- pipelines/pipeline.yml
- triggers/trigger-binding.yaml
- triggers/trigger-template.yaml
- triggers/trigger-rbac.yaml
